version: '3'
services:
  gateway:
    build: Gateway
    image: ra/gateway:0.0.1
    container_name: ra_gateway
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production 
      PORT: 8080
      EXPENSES_HOST: http://expenses
    restart: always

  expenses_db:
    image: mysql:5.7
    container_name: ra_expenses_db
    environment:
      MYSQL_DATABASE: expenses_prod
      MYSQL_USER: prod
      MYSQL_PASSWORD: ${EXPENSES_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${EXPENSES_DB_ROOT_PASSWORD}
    expose:
      - 3306
    volumes:
      - expenses:/var/lib/mysql
    restart: always
  
  expenses:
    build: Expenses
    image: ra/expenses:0.0.1
    container_name: ra_expenses
    depends_on:
      - gateway
      - expenses_db
    expose:
      - 80
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      EXPENSES_DB_PASSWORD: ${EXPENSES_DB_PASSWORD}
    restart: always

volumes:
  expenses: