version: '3'
services:
  budget-gateway:
    build: Gateway
    image: ra/budget-gateway:0.0.1
    container_name: ra-budget-gateway
    ports:
      - 8080:8080
      - 9876:9876
    environment:
      EXPENSES_API_URL: http://expenses/api/v1
    restart: always

  expenses_db:
    image: mysql:5.7
    container_name: ra_expenses_db
    environment:
      MYSQL_DATABASE: expenses_prod
      MYSQL_USER: prod
      MYSQL_PASSWORD: ${EXPENSES_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${EXPENSES_DB_ROOT_PASSWORD}
    expose:
      - 3306
    volumes:
      - expenses:/var/lib/mysql
    restart: always
  
  expenses:
    build: Expenses
    image: ra/expenses:0.0.1
    container_name: ra_expenses
    depends_on:
      - budget-gateway
      - expenses_db
    expose:
      - 80
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      EXPENSES_DB_PASSWORD: ${EXPENSES_DB_PASSWORD}
    restart: always

volumes:
  expenses: