http:
  port: 8080

admin:
  port: 9876
  host: localhost

apiEndpoints:
  api:
    host: "*"
    paths: [
      "/category/:id?",
      "/expense/:id?"
    ]

serviceEndpoints:
  api:
    url: ${EXPENSES_API_URL:-http://localhost:5000/api/v1}

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: api

