http:
  port: 8080

admin:
  port: 9876
  host: localhost

apiEndpoints:
  api:
    host: "*"
    paths: [
      "/category/:id?",
      "/expense/:id?"
    ]

serviceEndpoints:
  api:
    url: "http://expenses/api/v1"

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      -
        proxy:
          -
            action:
              serviceEndpoint: api